services:
  server:
    environment:
      ENABLE_SSL: "true"
      SSL_CERT_PATH: "/etc/ssl/my_certs/server.crt"
      SSL_KEY_PATH: "/etc/ssl/my_certs/server.key"
    volumes:
      - ssl_data:/etc/ssl/my_certs

volumes:
  ssl_data: