{{- if and .Values.enabled (not .Values.vaultAgent.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imap-service.fullname" . }}-secrets
  namespace: {{ include "imap-service.namespace" . }}
  labels:
    {{- include "imap-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: imap-service
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | quote }}
  TOKEN_SECRET_KEY: {{ .Values.secrets.tokenSecretKey | quote }}
  CRYPTO_KEY: {{ .Values.secrets.cryptoKey | quote }}
  IMAP_WEBHOOK_SECRET: {{ .Values.secrets.imapWebhookSecret | quote }}
{{- end }}
